#!/bin/bash
. ./pump-settings.sh

curl "http://$IP/set_alarm_host?host=$HOST_TEST_IP&port_hid=$HOST_TEST_PORT&port_hold=$HOLD_PORT&port_toolong=$TOOLONG_PORT"
curl "http://"$IP"/mode_signal_only"
# curl "http://"$IP"/reset_alarm_host"
